name: Setup pnpm and node.js for CI/CD
description: This action sets up pnpm and node.js for CI/CD workflows.

inputs:
  node-version:
    description: The version of Node.js to use
    required: true
    default: "24"
  pnpm-version:
    description: The version of pnpm to use
    required: true
    default: "11"

outputs:
  node-version:
    description: The version of Node.js that was set up
    value: ${{ steps.setup-node.outputs.node-version }}

runs:
  using: "composite"
  steps:
    - name: setup node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        
    - name: setup pnpm
      uses: pnpm/action-setup@v6
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.workspace }}
        pnpm install --frozen-lockfile
