name: ci-cd

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    project-lint:
        runs-on: ubuntu-24.04
        steps:
            -   uses: actions/checkout@v6
            -   uses: ./.github/actions/setup-pnpm-ci-cd
            -   name: Use EsLint
                run: pnpm run lint

    project-tests:
        runs-on: ubuntu-24.04
        steps:
            -   uses: actions/checkout@v6
            -   uses: ./.github/actions/setup-pnpm-ci-cd
            -   name: Test
                run: pnpm run test:run

    build:
        runs-on: ubuntu-24.04
        needs: [project-lint, project-tests]
        steps:
            -   uses: actions/checkout@v6
            -   uses: ./.github/actions/setup-pnpm-ci-cd
            -   name: Build
                run: pnpm build