name: ci

on:
    workflow_dispatch:

jobs:
    repo-files:
        runs-on: ubuntu-24.04
        steps:
            -   name: Download the base code
                uses: actions/checkout@v6
                
            -   name: list files
                run: ls -la